# Game
WINDOW_WIDTH = 360
WINDOW_HEIGHT = 640
WINDOW_TITLE = "Flappy Bird"
FPS = 60

GRAVITY = 900 # pixels per second ^ 2 (positive = down)

# Bird
BIRD_X = WINDOW_WIDTH // 8
BIRD_Y = WINDOW_HEIGHT // 2
BIRD_WIDTH = 34
BIRD_HEIGHT = 24
FLAP_VELOCITY = -300 # negative = up, pixels/sec

# Pipe
PIPE_X = WINDOW_WIDTH
PIPE_Y = 0
PIPE_WIDTH = 64
PIPE_HEIGHT = 512
PIPE_SPEED = 150
PIPE_GAP = 150
PIPE_INTERVAL = 1.6

GROUND_Y = 0